services:
  db:
    image: postgres:18.2-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: micro_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
